server:
  port: 5000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=limits
    username: postgres
    password: 123456
  flyway:
    schemas: limits
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      schema-locations: limits

initial-limit-amount: 10000
schedulers:
  restore-limit-task: "0 * * * * *"